name: pro_mana_example
description: "Demonstrates how to use the pro_mana plugin."

publish_to: 'none' 

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  pro_mana:
    path: ../
  # 前台服务
  flutter_background_service: ^5.0.10
  # 本地通知
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.1.1
  flutter_timezone: ^3.0.1
    # #耗电管理
  android_intent_plus: ^5.2.0
  cupertino_icons: ^1.0.8
  # #json格式转化功能
  # json_dynamic_widget: ^7.3.1+13
  #浮窗
  floating: ^5.0.1
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/appJson.json
 