name: pro_mana
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/usenameI/pro_mana.git
publish_to: none  # 添加这一行
environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  #获取经纬度
  geolocator: ^13.0.1
  #获取权限
  permission_handler: ^11.3.1
  #编辑图片
  image: ^4.3.0
  #重力感应器
  sensors_plus: ^4.0.1
  # 裁剪
  crop_your_image: ^1.1.0
  # 组件库
  # tdesign_flutter: ^0.1.8
  tdesign_flutter:
    path: ../tdesign-flutter-0.1.8/tdesign-flutter-0.1.8/tdesign-component
  # tdesign_flutter:
  #   git:
  #     url: 'https://github.com/bomb-bomb/tdesign-flutter'
  #     path: 'tdesign-component'
  #微信相册
  wechat_assets_picker: ^9.4.2
  #微信相机
  wechat_camera_picker: ^4.3.6
  #图片预览
  photo_view: ^0.15.0
    # 屏幕参数适配 https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0
  #跳转第三方
  url_launcher: ^6.3.1
  #坐标系转换
  coordtransform_dart: ^1.0.4
  #网络请求插件
  dio: ^5.8.0+1
  #本地存储
  shared_preferences: ^2.5.1
  #状态管理
  provider: ^6.1.2
  #日期范围
  # syncfusion_flutter_datepicker: ^27.2.5
  #底部菜单
  convex_bottom_bar: ^3.2.0
  #列表的底部菜单
  flutter_floating_bottom_bar: ^1.2.1+1
  #跳转权限设置插件
  app_settings: ^5.1.1
  # #耗电管理
  # android_intent_plus: ^5.2.0
  # 本地通知
  flutter_local_notifications: ^18.0.1
  #路径获取
  path_provider: ^2.1.5
  # 签名涂鸦
  signature: ^5.5.0
  #弹窗选择
  custom_pop_up_menu: ^1.2.4
  #视频剪辑
  video_trimmer: ^3.0.1

  image_painter: 
    path: ../yellowQ-Flutter-Image-Painter-main (1)/yellowQ-Flutter-Image-Painter-main
  open_file: ^3.3.2
  #图表库
  syncfusion_flutter_charts: ^27.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
dependency_overrides: 
  path: ^1.9.1 
flutter:
  plugin:
    platforms:
    # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------
      android:
        package: com.example.pro_mana
        pluginClass: ProManaPlugin